apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  
  name: configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awesome-mutator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: default  # Replace with your namespace
subjects:
  - kind: ServiceAccount
    name: awesome-mutator-sa  # The name of the service account your pod uses
    namespace: default        # Replace with your namespace
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
