apiVersion: v1
kind: Pod
metadata:
  name: test-pod-agentpool
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  nodeSelector:
    agentpool: copprfpool
  containers:
    - name: nginx
      image: nginx