{{- if .Values.maxUnavailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "awesome-mutator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "awesome-mutator.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
        {{- include "awesome-mutator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}