apiVersion: v1
kind: Service
metadata:
  name: awesome-mutator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "awesome-mutator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "awesome-mutator.selectorLabels" . | nindent 4 }}